### PR TITLE
add Arksec logo in Harbor Adopters

### PR DESCRIPTION
**Pull request by simonsuns**
add Arksec logo in Harbor Adopters

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@simonsuns - can I ask you if possible to fill in this https://github.com/goharbor/community/issues/115! :) Will be very helpful to collect that data!

**Comment by OrlinVasilev** [comment]
@simonsuns any update on that please?

**Comment by a-mccarthy** [comment]
Am i looking at this right? it looks like this image is already added to the docs/img/adopters folder

@simonsuns @OrlinVasilev

**Comment by OrlinVasilev** [comment]
yup it was and merged we are waiting @simonsuns to add the info into https://github.com/goharbor/community/issues/115
Really like how we do it for Contour https://github.com/projectcontour/contour/blob/main/ADOPTERS.md

**Pull request closed without merging**
