### PR TITLE
fix helm push command

### PR DESCRIPTION
**Pull request by smartbit**
See https://github.com/chartmuseum/helm-push#push-tgz-package

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@smartbit thank you for this PR, can you sign the commit? https://github.com/goharbor/website/pull/270/checks?check_run_id=4455651641

**Comment by a-mccarthy** [comment]
@smartbit ping again here to see if you are willing to sign your commits? We can't merge this PR in without signed commits. More info: https://github.com/goharbor/website/pull/270/checks?check_run_id=4455651641

**Comment by OrlinVasilev** [comment]
@smartbit - hi there are can you please fix the signature of your commits please ! :)

**Comment by OrlinVasilev** [comment]
@smartbit congrats on merging your first PR here :) welcome to the club :)

**Pull request merged**
