### PR TITLE
docs: update webhook related document

### PR DESCRIPTION
**Pull request by chlins**
1. Update the webhook payload introduction document, add example JSON payload for every event type.
2. Add the document for CloudEvents webhook payload.

Fixes: https://github.com/goharbor/harbor/issues/14865

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]
LGTM :)

**Comment by OrlinVasilev** [comment]
@slushysnowman can you can these as well please :)

**Comment by OrlinVasilev** [comment]
@chlins the branch has some conflicts can you fix them please

**Review by wy65701436 — APPROVED** [review]
LGTM

**Review by AllForNothing — APPROVED** [review]
lgtm

**Pull request merged**
