### PR TITLE
Fix exemple 5 results

### PR DESCRIPTION
**Pull request by jerCarre**
Fix number of rules
Fix results : add `4.4-your_repo-prod` because of second rule

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]
thank you!

**Comment by OrlinVasilev** [comment]
@jerCarre please sign your commits so you can fix the DCO requirements 
something like "git commit --amend -s"

**Review by AllForNothing — APPROVED** [review]

**Comment by jerCarre** [comment]
I just add my signature in my account. The commit appears as verified now.

**Comment by a-mccarthy** [comment]
@jerCarre thanks for looking into the DCO. The PR checks are still showing as fail. Were you able to push the signed commit to this PR? More details on resolving the DCO check failure can be found here, https://github.com/goharbor/website/pull/340/checks?check_run_id=6863105875

**Comment by AllForNothing** [comment]
I should have waited for his signing,   but accidentally clicked the "squash and merge" button

**Pull request merged**
