### PR TITLE
Add CERN as adopter

### PR DESCRIPTION
**Pull request by OrlinVasilev**

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@rochaporto for visibility :) thank you!!

**Comment by OrlinVasilev** [comment]
@Vad1mo @wy65701436 can you please review this

**Review by Vad1mo — APPROVED** [review]

**Comment by Vad1mo** [comment]
@zyyw @wy65701436 , can you approve

**Comment by OrlinVasilev** [comment]
heyy that took just 10 months:)

**Review by zyyw — APPROVED** [review]

**Pull request merged**
