### PR TITLE
fix OIDC typo

### PR DESCRIPTION
**Pull request by MinerYang**
Signed-off-by: yminer <yminer@vmware.com>

### CODE REVIEW

**Review by chlins — APPROVED** [review]
lgtm

**Comment by MinerYang** [comment]
Hi @OrlinVasilev,
Could you please help to take a look at this CI in the branch `release-1.10`. It failed twice and we have no I idea is it still work or not. Appreciate!

Best,
Miner

**Comment by OrlinVasilev** [comment]
@MinerYang can you do another push to re-trigger the checks please

**Comment by MinerYang** [comment]
> @MinerYang can you do another push to re-trigger the checks please

Yes. Actually I have tried to push twice before but no changes.

**Comment by OrlinVasilev** [comment]
@MinerYang is that change only valid of 1.10?

**Comment by OrlinVasilev** [comment]
the checks will never pass since in the branch for 1.10 we don't have any of the build scripts

**Pull request merged**
