### PR TITLE
Resolved a small error in the documentation

### PR DESCRIPTION
**Pull request by Xander23432**
Small Grammatical change to the tech-docs

harbor-techdoc-contribution

### CODE REVIEW

**Review by a-mccarthy — APPROVED** [review]
lgtm

**Comment by a-mccarthy** [comment]
@Xander23432 thanks for the contribution!

**Comment by Xander23432** [comment]
Your Welcome

**Comment by Xander23432** [comment]
_**@a-mccarthy**_ The pleasure is all mine

**Pull request merged**
