### PR TITLE
Update create-robot-accounts.md

### PR DESCRIPTION
**Pull request by eugeneivanov101**
Signed-off-by: Eugene Ivanov <eivanov427@gmail.com>

Replace `disable(d)` with `deactivate(d)`

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@eugeneivanov101 there are some conflicts can you please fix them here a good video how to do it https://www.youtube.com/watch?v=mOJazBNrG-c

Also if you please rebase your branch with the main so you can have updated I suppose more will pop-up, good article how you can do that you can find here: https://www.freecodecamp.org/news/the-ultimate-guide-to-git-merge-and-git-rebase/

**Comment by eugeneivanov101** [comment]
@OrlinVasilev I believe I did both.

**Comment by OrlinVasilev** [comment]
@eugeneivanov101 Yeah now looks much better! in the previous commit you had already existing pages! Thanks

**Review by OrlinVasilev — APPROVED** [review]
LGTM

**Comment by OrlinVasilev** [comment]
@a-mccarthy can you take a look as well:) Thanks!

**Comment by OrlinVasilev** [comment]
@eugeneivanov101 made some comments please check and fix :)

**Review by OrlinVasilev — COMMENTED** [review]
please fix the outlined issues

**Review by OrlinVasilev — CHANGES_REQUESTED** [review]
please fix the merge conflicts left overs

**Comment by eugeneivanov101** [comment]
@OrlinVasilev I have a problem: once I make the suggested edit to `docs/install-config/configure-yml-file.md` to `patch-1`, I get the DCO issue. Once I resolve the DCO issue, I get the conflict back. What to do?

**Comment by eugeneivanov101** [comment]
@OrlinVasilev Looks like I fixed the problem?

**Comment by OrlinVasilev** [comment]
@eugeneivanov101 - sorry for not responding , Easter holiday here :) 
Looks like you did not for example .backportrc.json that file should not be in your change :(

**Review by OrlinVasilev — APPROVED** [review]
lgtm

**Pull request merged**
