### PR TITLE
Add NS as Harbor adopter

### PR DESCRIPTION
**Pull request by slushysnowman**

### CODE REVIEW

**Comment by Vad1mo** [comment]
awesome, I  think you should also add  the listing to the yaml.

see https://github.com/goharbor/website/pull/467/files for reference.

**Review by Vad1mo — APPROVED** [review]

**Comment by slushysnowman** [comment]
> awesome, I think you should also add the listing to the yaml.
> 
> see https://github.com/goharbor/website/pull/467/files for reference.

Should I include that in this PR? Probably makes sense I guess?

**Comment by Vad1mo** [comment]
yes, all in one

**Comment by slushysnowman** [comment]
> yes, all in one

Done!

**Comment by OrlinVasilev** [comment]
@slushysnowman thanks for that :)) it's great to see the adoption :)
do you mind resizing static/img/logos/users-partners/nederlandse-spoorwegen-logo.png to 150px by whatever comes so it can be properly displayed in https://github.com/goharbor/harbor/blob/main/ADOPTERS.md otherwise it will be HUGE :)

**Review by OrlinVasilev — APPROVED** [review]

**Pull request merged**
