### PR TITLE
Update user-permissions-by-role.md

### PR DESCRIPTION
**Pull request by eugeneivanov101**
Signed-off-by: Eugene Ivanov <eivanov427@gmail.com> 

Replaced `disable` with `deactivate` on lines 55, 57, and 59 (issue #303)

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@eugeneivanov101 you should fix the description so DCO can pass

**Review by OrlinVasilev — COMMENTED** [review]
needs DCO fix

**Comment by eugeneivanov101** [comment]
@a-mccarthy @OrlinVasilev Looks like I fixed the DCO issue.

**Review by OrlinVasilev — APPROVED** [review]
lgtm

**Pull request merged**
