### PR TITLE
Fix link in storage docs to Docker Registry Configuration

### PR DESCRIPTION
**Pull request by edbaunton**
All the registry docs have moved to Distribution per https://docs.docker.com/registry/

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]

**Review by AllForNothing — APPROVED** [review]
lgtm

**Comment by AllForNothing** [comment]
@edbaunto Thanks for the contribution!!!

**Comment by OrlinVasilev** [comment]
@edbaunton congrats on your first PR merged here :) welcome to the club! :)

**Comment by edbaunton** [comment]
Thanks! :) Hopefully the first of many. Thanks for the quick review and merge.

**Pull request merged**
