### PR TITLE
Fix figures in tables so they show up a normal size

### PR DESCRIPTION
**Pull request by a-mccarthy**
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@jonasrosland can you review this? Meant to fix images in the tables here - https://deploy-preview-161--goharbor-io.netlify.app/docs/edge/install-config/harbor-compatibility-list/ 

Can you think of any other pages with images in tables or tables wee should make sure aren't affected by this change

**Comment by jonasrosland** [comment]
Taking a look.
Not related to this, but another table issue shows up on https://deploy-preview-161--goharbor-io.netlify.app/docs/edge/install-config/configure-yml-file/ - the table is too wide. Perhaps we should widen the docs are in general? Might be worth looking into.

**Comment by jonasrosland** [comment]
Same thing with the tables on https://deploy-preview-161--goharbor-io.netlify.app/docs/edge/install-config/configure-user-settings-cli/ and https://deploy-preview-161--goharbor-io.netlify.app/docs/edge/build-customize-contribute/registry-landscape/ - too wide for the page.

Everything else looks good!

**Review by jonasrosland — APPROVED** [review]

**Comment by a-mccarthy** [comment]
@jonasrosland thanks for the review, i created #162 to look into thee wide tables issue

**Pull request merged**
