### PR TITLE
[cherry-pick]Update docker distribution to Distribution/Distribution

### PR DESCRIPTION
**Pull request by YangJiao0817**

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by Vad1mo** [comment]
**Docker Distribution** is not the correct name anymore, Distribution Distribution is not correct either!

I would rather reference it as **"Distribution/Distribution"**, like the GitHub project name or as **OCI Distribution Toolkit**, as it is named in the title.

**Comment by YangJiao0817** [comment]
> **Docker Distribution** is not the correct name anymore, Distribution Distribution is not correct either!
> 
> I would rather reference it as **"Distribution/Distribution"**, like the GitHub project name or as **OCI Distribution Toolkit**, as it is named in the title.

@Vad1mo Ok, I have updated to **Distribution/Distribution**

**Review by MinerYang — APPROVED** [review]
lgtm

**Pull request merged**
