### PR TITLE
Add PITS Globale Datenrettungsdienste as adopter

### PR DESCRIPTION
**Pull request by arnoldberlin**
Uploaded PITS Globale Datenrettungsdienste logo. 
Realted PR https://github.com/goharbor/harbor/pull/18884.

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]
lgtm

**Comment by OrlinVasilev** [comment]
@arnoldberlin thanks for adding your company :)) so cool to see that maybe we can discuss a bit more over zoom ? 
BTW do you mind also adding it into the site section as well like https://github.com/goharbor/website/pull/473/files
so we can have it consistent thanks!

**Review by Vad1mo — CHANGES_REQUESTED** [review]
Why are there two image files?

**Comment by OrlinVasilev** [comment]
@Vad1mo the static/img/logos/users-partners/pits-globale-datenrettungsdienste.png is needed for the main repository adopters.md ... the whole process is a bit clanky so we have to rework it as I proposed a few times already :)

**Review by OrlinVasilev — APPROVED** [review]
looks super good to me :)) thanks @arnoldberlin

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
