### PR TITLE
fixes name of metrics endpoint

### PR DESCRIPTION
**Pull request by Brice187**

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
Hi @Brice187, thanks for that!!! I'm missing the issue here, so can you help me out where this  "http" comes from? :) thank you so much!

**Comment by Brice187** [comment]
> Hi @Brice187, thanks for that!!! I'm missing the issue here, so can you help me out where this "http" comes from? :) thank you so much!

https://github.com/goharbor/harbor-helm/blob/c8853808bd657359ed8fba454c45fd2b98862c3c/templates/_helpers.tpl#L465

**Review by OrlinVasilev — APPROVED** [review]
Thank you I was looking exactly for this!

**Comment by OrlinVasilev** [comment]
@Brice187 thanks for that :) and welcome to the club!

**Comment by OrlinVasilev** [comment]
🖖 (closest to the boy scout) :) haha

**Pull request merged**
