### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by harryfeng72**

### CODE REVIEW

**Comment by steven-zou** [comment]
@harryfeng72 

Why is your PR based on release-2.3.0? I think the change should be based on master.

**Comment by a-mccarthy** [comment]
@harryfeng72 can you explain more about what you are trying to add with this PR? looking at the docs, it seems like those changes are already there, https://github.com/goharbor/website/blob/master/docs/administration/upgrade/_index.md and https://goharbor.io/docs/edge/administration/upgrade/

**Comment by a-mccarthy** [comment]
@harryfeng72 ping again here to see if you can provide more context for this PR? thanks!

**Comment by a-mccarthy** [comment]
@harryfeng72 going to close this. please reopen if you you still want these changes made

**Pull request closed without merging**
