### PR TITLE
Update outdated swagger info

### PR DESCRIPTION
**Pull request by a-mccarthy**
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>

fixes https://github.com/goharbor/website/issues/118 and https://github.com/goharbor/harbor/issues/13552

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@heww do you have time to review this PR that removes outdated information about the swagger ui from the docs site and updates the docs on how to access the swaggeer UI from the portal. thanks!

Is there anything else we should include in the docs to help users with the swagger UI? 

Is the URL correct `https://<harbor_ip>/devcenter` for getting to the swagger UI?

**Comment by a-mccarthy** [comment]
@heww ping! do you have a minute to look at this, thanks!

**Comment by a-mccarthy** [comment]
@heww do you have time to review this pr? thanks!

**Review by heww — APPROVED** [review]
LGTM

**Pull request merged**
