### PR TITLE
Confirm Cyberwatch scanner eval after community meeting

### PR DESCRIPTION
**Pull request by tarraschk**
Add Yes to the Cyberwatch scanner Evaluation, based on the demonstration we made on June 14th 2023 (https://github.com/goharbor/community/wiki/Harbor-Community-Meetings#june-14-2023)

### CODE REVIEW

**Comment by tarraschk** [comment]
little bump if a second reviewer can also read this little PR and approve it :)

**Comment by OrlinVasilev** [comment]
@Vad1mo @wy65701436 bump here thanks

**Review by Vad1mo — APPROVED** [review]

**Comment by tarraschk** [comment]
Thanks @Vad1mo 

@wy65701436 could you review also the PR? Thanks

**Comment by fwininger** [comment]
@Vad1mo thanks :)

**Pull request merged**
