### PR TITLE
Add job service dashboard document

### PR DESCRIPTION
**Pull request by stonezdj**
Signed-off-by: stonezdj <daojunz@vmware.com>

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
TOC is not rendering properly

**Comment by stonezdj** [comment]
> TOC is not rendering properly

Could you please paste the screenshot?  it seems to work in my local env
Screen Shot 2022-12-02 at 11 20 22

**Comment by OrlinVasilev** [comment]
image

**Comment by OrlinVasilev** [comment]
it's visible only in edge

**Comment by stonezdj** [comment]
> it's visible only in edge

Yes, because the PR is going to merge into main branch, only visible in edge, after that we should create a tag/branch for 2.7.0 release, then it visible in the 2.7.0 release.

**Review by OrlinVasilev — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
