### PR TITLE
Add Alauda as partners

### PR DESCRIPTION
**Pull request by mirake**
Add Alauda as partner. Thanks

### CODE REVIEW

**Review by steven-zou — APPROVED** [review]
`Alauda` is a close partner.

**Review by chlins — APPROVED** [review]
lgtm

**Review by Vad1mo — CHANGES_REQUESTED** [review]
there is an error in the preview

image

**Comment by mirake** [comment]
@Vad1mo  Sorry, maybe the image is in the wrong directory.  I upload the image again, I think this time it is right. Thanks

**Comment by OrlinVasilev** [comment]
@mirake - two things: 
- How do we partner ? 
- the partners are sorted alphabetically, can you please fix that ?

**Review by OrlinVasilev — CHANGES_REQUESTED** [review]
- the partners are sorted alphabetically, can you please fix that ?

**Comment by mirake** [comment]
> @mirake - two things:
> 
> * How do we partner ?
> * the partners are sorted alphabetically, can you please fix that ?

 Thanks,  @OrlinVasilev . For your two questions

* We provide a range of services for Harbor in China, supporting multiple clients with upgrades, troubleshooting, optimization, and scaling. Our product, the Alauda Container Platform, integrates seamlessly with Harbor, making it a key component of our enterprise delivery services.
* I've updated partners.yaml alphabetically.

**Comment by mirake** [comment]
> Thanks, @OrlinVasilev . For your two questions
> 
> * We provide a range of services for Harbor in China, supporting multiple clients with upgrades, troubleshooting, optimization, and scaling. Our product, the Alauda Container Platform, integrates seamlessly with Harbor, making it a key component of our enterprise delivery services.
> * I've updated partners.yaml alphabetically.

Hi, @OrlinVasilev ,  could you please review this ?

**Comment by danielfbm** [comment]
@OrlinVasilev is there anything we can do further to help?

**Review by OrlinVasilev — APPROVED** [review]

**Pull request merged**
